# Generated by Django 5.0.7 on 2025-03-17 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0002_post_author_post_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 18, 0, 6, 35, 799497)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 18, 0, 6, 35, 799497)
            ),
        ),
    ]
